select USER_NAME, QUERY_TEXT, MODEL, LOGGED_AT, SEARCH_LATENCY_MS, COMPLETE_LATENCY_MS, PROMPT_TOKENS, COMPLETION_TOKENS,
    TOTAL_TOKENS, TOKEN_CREDITS, SEARCH_RESULTS_COUNT
from SALES_INTELLIGENCE.CORE.QUERY_USAGE_LOG
order by logged_at desc