//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sparq.SnowflakeAdvanced.OracleCortextAnalyst.DataAccess {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Queries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sparq.SnowflakeAdvanced.OracleCortextAnalyst.DataAccess.Queries", typeof(Queries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT SNOWFLAKE.CORTEX.COMPLETE(
        ///    ?,
        ///    ARRAY_CONSTRUCT(
        ///        OBJECT_CONSTRUCT(&apos;role&apos;, &apos;system&apos;, &apos;content&apos;,
        ///            &apos;You are a Sales Operations assistant. Answer the user&apos;&apos;s question using ONLY the provided context from contracts, slides, and transcripts. &apos; +
        ///            &apos;If the answer isn&apos;&apos;t in the context, say you don&apos;&apos;t know. Be precise with legal terms.&apos;),
        ///        OBJECT_CONSTRUCT(&apos;role&apos;, &apos;user&apos;, &apos;content&apos;, ?)
        ///    ),
        ///    OBJECT_CONSTRUCT(&apos;temperature&apos;, 0.2, &apos;max_tokens&apos;, 1024)
        ///) AS  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CortexComplete {
            get {
                return ResourceManager.GetString("CortexComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT CHUNK_ID, FILE_NAME, FILE_TYPE, CHUNK_INDEX, RAW_TEXT_SEGMENT, CLEANED_TEXT_SEGMENT, SECTION_CONTEXT, EMBEDDING_VECTOR
        ///FROM SALES_INTELLIGENCE.CORE.DOCUMENT_CHUNKS;.
        /// </summary>
        internal static string GetDocumentChunks {
            get {
                return ResourceManager.GetString("GetDocumentChunks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT FILE_NAME, FILE_TYPE, FILE_SIZE, RAW_TEXT, CLEANED_TEXT, LOADED_AT, CONTENT_HASH
        ///FROM SALES_INTELLIGENCE.CORE.DOCUMENTS;.
        /// </summary>
        internal static string GetDocuments {
            get {
                return ResourceManager.GetString("GetDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select USER_NAME, QUERY_TEXT, MODEL, LOGGED_AT, SEARCH_LATENCY_MS, COMPLETE_LATENCY_MS, PROMPT_TOKENS, COMPLETION_TOKENS,
        ///    TOTAL_TOKENS, TOKEN_CREDITS, SEARCH_RESULTS_COUNT
        ///from SALES_INTELLIGENCE.CORE.QUERY_USAGE_LOG
        ///order by logged_at desc.
        /// </summary>
        internal static string GetQueryUsage {
            get {
                return ResourceManager.GetString("GetQueryUsage", resourceCulture);
            }
        }
    }
}
